---
- name: Set reachable to false
  ansible.builtin.set_fact:
    setup_ok: nologin

- name: Minimal setup
  become: true
  ansible.builtin.setup:
    # gather_timeout: 60
  async: "{{ async_delay }}"
  poll: "{{ poll_count }}"

- name: Set reachable to true
  ansible.builtin.set_fact:
    setup_ok: true
