---
- name: Check oom killer was active
  block:
    - name: Run dmesg
      ansible.builtin.shell:
        cmd: /bin/dmesg -T | grep  'invoked oom-killer'
      register: oom
      changed_when: false
      ignore_errors: true
      failed_when: false
      no_log: false
      become: true
  rescue:
    - name: Set empty result if grep fails
      ansible.builtin.set_fact:
        oom: { rc: 1, stdout: "", stderr: "" }

- name: Set_fact oom_last_outcome
  ansible.builtin.set_fact:
    oom_last_outcome: "{{ oom.stdout_lines[-1].split(']')[0].split('[')[-1] }}"
  when: not oom.rc
