---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.include_role:
        name: zilux.core.report
        tasks_from: oom_check
