---
driver:
  name: default
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: default

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

platforms:
  - name: harry-dev-oom
    image: registry.access.redhat.com/ubi9/ubi-init
    volume:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    priviledged: true
    cap_add:
      - CAP_SYSLOG
      - CAP_SYS_ADMIN

provisioner:
  name: ansible
  config_options:
    defaults:
      inventory: ./inventory
      stdout_callback: yaml
      roles_path: ../../roles
      deprecation_warnings: false
      remote_user: root
      local_tmp: /tmp/.ansitemp
    # playbooks:
    #   converge: ../../../../playbooks/run_report.yml
    #   create: ../../../../playbooks/test_play.yml
    # env:
    #   ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"
    #   ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../.."

scenario:
  name: oom
  test_sequence:
  # - destroy
    - dependency
    - create
  # - prepare
    - converge
    - verify
  # - destroy

verifier:
  name: ansible
